### ISSUE TITLE
Update Data

### ISSUE THREAD

**Issue by ghost** [opendatalab-de/simple-geodata-selector#1]
In 2016 there were changes in the keys for some areas. In [2016.xls](https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=1&ved=2ahUKEwiw6JSn5PbfAhVDKewKHdipC_cQFjAAegQIChAC&url=https%3A%2F%2Fwww.destatis.de%2FDE%2FZahlenFakten%2FLaenderRegionen%2FRegionales%2FGemeindeverzeichnis%2FNamensGrenzAenderung%2FAktuell%2F2016.xls%3F__blob%3DpublicationFile&usg=AOvVaw1NZUAViK5I1CeV0B5ErGhh) you can find these changes. I got the problem that "Landkreis Göttingen" changed the AGS, so that I can't map it with other data. In my case this is the only problem until now, but maybe there will be more for others.

**Comment by grundid** [comment]
Hi. Thank you for your feedback. How urgent do you need the update? I'll try to put this topic on our OpenDataDay Hackathon on 2.3.2019. We should have an update after this.

**Comment by ghost** [comment]
That is perfectly fine, thank you for your support.

**Comment by derhuerst** [comment]
friendly ping (:
